
services:
  app:
    container_name: gira-api
    image: node:18-alpine
    command: npm run start:dev
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    container_name: gira-postgres
    image: postgres:alpine
    volumes:
      - gira-postgres-data:/var/lib/postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
    expose:
      - "${DB_PORT}"
    restart: always
    command: -p ${DB_PORT}


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  gira-postgres-data: