name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PORT: ${{ secrets.PORT }}
  CRUD_SERVICE_HOST: ${{ secrets.CRUD_SERVICE_HOST }}
  CRUD_SERVICE_PORT: ${{ secrets.CRUD_SERVICE_PORT }}

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
